services:
  rust_devcontainer:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    restart: always
    tty: true
    volumes:
      - ../:/workspace
    working_dir: /workspace
    env_file:
      - .env